### ISSUE TITLE
auxiliary python files missing

### ISSUE THREAD

**Issue by MiroljubA** [enggen/Deep-Learning-Coursera#1]
Hi enggen, 
quite good that you've downloaded all the coursework materials but I've noticed you didn't download the auxiliary python files. that would be a nice addition.

**Comment by enggen** [comment]
hi, I can do that but i'm not sure if we are allowed to put all the course resources on open github.

**Comment by MiroljubA** [comment]
yes, that's true.
But you are not allowed to put any files from Coursesa courses on github without their permission...

**Comment by ghost** [comment]
well, how can I download them legally from the course? I keep getting messages like "testCases" not found and the like
